In [81]:
import numpy as np
import pandas as pd

# Data Analysis

In [82]:
 url = "https://raw.githubusercontent.com/reddy-nithin/PDS-Assignments/refs/heads/main/Assignment%202/Clean%20Data/clean_data_cars.csv"
 df = pd.read_csv(url)
 df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,0,0,1
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,0,0,1
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,0,0,0
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,0,0,1

### Adding more Features

In [83]:
from datetime import datetime

current_year = datetime.now().year
df['Car_Age'] = current_year - df['Year']
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,0,0,1,9
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1,13
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,0,0,1,12
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,0,0,0,11
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,0,0,1,11

In [84]:
usage_threshold = 50000
df['Usage_Category'] = df['Kilometers_Driven'].apply(
    lambda km: 'Fairly Used' if km < usage_threshold else 'Used More')
df.head()

,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Owner_Type,Mileage,Engine,Power,Seats,Price,Fuel_Type_Electric,Fuel_Type_Petrol,Transmission_Manual,Car_Age,Usage_Category
0,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,First,19.67,1582.0,126.20,5.0,12.50,0,0,1,9,Fairly Used
1,2,Honda Jazz V,Chennai,2011,46000,First,18.19,1199.0,88.70,5.0,4.50,0,1,1,13,Fairly Used
2,3,Maruti Ertiga VDI,Chennai,2012,87000,First,20.77,1248.0,88.76,7.0,6.00,0,0,1,12,Used More
3,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Second,15.20,1968.0,140.80,5.0,17.74,0,0,0,11,Fairly Used
4,6,Nissan Micra Diesel XV,Jaipur,2013,86999,First,23.08,1461.0,63.10,5.0,3.50,0,0,1,11,Used More

### Performing select, filter, rename, mutate, arrange and summarize with group by operations  on this dataset.

In [85]:
# Using Select and Filter
selected_data = df[['Name', 'Location', 'Car_Age', 'Mileage', 'Price', 'Usage_Category']]
filtered_data = selected_data[(selected_data['Car_Age'] <= 5) & (selected_data['Price'] < 1000000) & (selected_data['Usage_Category'] == 'Fairly Used')]
filtered_data

,Name,Location,Car_Age,Mileage,Price,Usage_Category
65,Mercedes-Benz C-Class Progressive C 220d,Coimbatore,5,0.00,35.67,Fairly Used
128,Hyundai Verna VTVT 1.6 AT SX Plus,Kochi,5,17.00,11.50,Fairly Used
147,Hyundai EON Magna Plus,Kochi,5,21.10,4.23,Fairly Used
165,Hyundai Grand i10 1.2 Kappa Asta,Kolkata,5,18.90,6.50,Fairly Used
226,Toyota Innova Crysta 2.8 GX AT,Kochi,5,11.36,19.64,Fairly Used
...,...,...,...,...,...,...
5608,Tata Tiago 1.2 Revotron XZ,Coimbatore,5,23.84,6.94,Fairly Used
5628,Renault KWID RXL,Kochi,5,25.17,3.80,Fairly Used
5644,Skoda Rapid 1.6 MPI Ambition,Coimbatore,5,15.41,9.66,Fairly Used
5699,Mahindra Thar CRDe AC,Coimbatore,5,16.55,10.36,Fairly Used
5712,Mercedes-Benz C-Class Progressive C 220d,Ahmedabad,5,0.00,35.00,Fairly Used

In [86]:
# Renaming columns for better clarity
filtered_data = filtered_data.rename(columns={'Name': 'Car_Model', 'Price': 'Price_when_new(Lakhs)'})
filtered_data.head()

,Car_Model,Location,Car_Age,Mileage,Price_when_new(Lakhs),Usage_Category
65,Mercedes-Benz C-Class Progressive C 220d,Coimbatore,5,0.00,35.67,Fairly Used
128,Hyundai Verna VTVT 1.6 AT SX Plus,Kochi,5,17.00,11.50,Fairly Used
147,Hyundai EON Magna Plus,Kochi,5,21.10,4.23,Fairly Used
165,Hyundai Grand i10 1.2 Kappa Asta,Kolkata,5,18.90,6.50,Fairly Used
226,Toyota Innova Crysta 2.8 GX AT,Kochi,5,11.36,19.64,Fairly Used

In [87]:
# Mutating the data with new "Car_Make" Column
filtered_data['Car_Make'] = filtered_data['Car_Model'].str.split().str[0]
filtered_data.Car_Make.head()

65     Mercedes-Benz
128          Hyundai
147          Hyundai
165          Hyundai
226           Toyota
Name: Car_Make, dtype: object

In [88]:
# Arranging data by 'Selling_Price' in ascending order
arranged_data = filtered_data.sort_values(by='Price_when_new(Lakhs)')
arranged_data.head()

,Car_Model,Location,Car_Age,Mileage,Price_when_new(Lakhs),Usage_Category,Car_Make
3033,Porsche Cayenne Base,Kochi,5,13.33,2.02,Fairly Used,Porsche
4305,Maruti Alto 800 2016-2019 LXI Optional,Jaipur,5,24.70,3.50,Fairly Used,Maruti
1315,Maruti Alto 800 2016-2019 VXI,Mumbai,5,24.70,3.60,Fairly Used,Maruti
2413,Maruti Alto 800 2016-2019 VXI,Kochi,5,24.70,3.80,Fairly Used,Maruti
5628,Renault KWID RXL,Kochi,5,25.17,3.80,Fairly Used,Renault

In [89]:
# Summarizing with Group By: Calculating the average price by 'Location' for cars
summary = arranged_data.groupby('Location').agg(Average_Selling_Price=('Price_when_new(Lakhs)', 'mean')).reset_index()
summary.head()

     Location  Average_Selling_Price
0   Ahmedabad              35.000000
1     Chennai              34.200000
2  Coimbatore              22.107209
3   Hyderabad               5.680000
4      Jaipur               3.500000